databases:
  - name: healthcare-db
    plan: free
    databaseName: healthcare_db
    region: singapore

services:
  - type: web
    name: healthcare-user-svc
    runtime: python
    plan: free
    region: singapore
    rootDir: user-service
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --preload
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: healthcare-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: "false"
      - key: OTEL_SERVICE_NAME
        value: user-service

  - type: web
    name: healthcare-appt-svc
    runtime: python
    plan: free
    region: singapore
    rootDir: appointment-service
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --preload
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: healthcare-db
          property: connectionString
      - key: JWT_SECRET_KEY
        fromService:
          name: healthcare-user-svc
          type: web
          envVarKey: JWT_SECRET_KEY
      - key: USER_SERVICE_URL
        value: https://healthcare-user-svc.onrender.com
      - key: FLASK_DEBUG
        value: "false"
      - key: OTEL_SERVICE_NAME
        value: appointment-service

  - type: web
    name: healthcare-report-svc
    runtime: python
    plan: free
    region: singapore
    rootDir: report-service
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --preload
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: healthcare-db
          property: connectionString
      - key: JWT_SECRET_KEY
        fromService:
          name: healthcare-user-svc
          type: web
          envVarKey: JWT_SECRET_KEY
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_BUCKET
        sync: false
      - key: AWS_S3_REGION
        value: ap-southeast-1
      - key: FLASK_DEBUG
        value: "false"
      - key: OTEL_SERVICE_NAME
        value: report-service

  - type: web
    name: healthcare-app
    runtime: node
    plan: free
    region: singapore
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l $PORT
    envVars:
      - key: REACT_APP_USER_SERVICE_URL
        value: https://healthcare-user-svc.onrender.com
      - key: REACT_APP_APPOINTMENT_SERVICE_URL
        value: https://healthcare-appt-svc.onrender.com
      - key: REACT_APP_REPORT_SERVICE_URL
        value: https://healthcare-report-svc.onrender.com
